In [1]:
import LanusStats as ls
import pandas as pd 

fbref = ls.Fbref()
fotmo = ls.FotMob()
score = ls.ThreeSixFiveScores()

In [30]:
ls.get_available_pages()

dict_keys(['Fbref', 'Sofascore', '365Scores', 'Fotmob', 'Transfermarkt'])

In [3]:
ls.get_available_leagues('Fbref')

['Copa de la Liga',
 'Primera Division Argentina',
 'Primera Division Uruguay',
 'Brasileirao',
 'Brasileirao B',
 'Primera Division Colombia',
 'Primera Division Chile',
 'Primera Division Peru',
 'Primera Division Venezuela',
 'Primera Division Ecuador',
 'Primera Division Bolivia',
 'Primera Division Paraguay',
 'Brasileirao F',
 'MLS',
 'USL Championship',
 'Premier League',
 'La Liga',
 'Ligue 1',
 'Bundesliga',
 'Serie A',
 'Big 5 European Leagues',
 'Danish Superliga',
 'Eredivise',
 'Primeira Liga Portugal',
 'Copa America',
 'Euros',
 'Saudi League',
 'EFL Championship',
 'La Liga 2',
 'Belgian Pro League',
 'Challenger Pro League',
 '2. Bundesliga',
 'Ligue 2',
 'Serie B',
 'J1 League',
 'NSWL',
 'Wowens Super League',
 'Liga F',
 'Premier Division South Africa',
 'Champions League',
 'Europa League',
 'Conference League',
 'Copa Libertadores']

In [23]:
ls.get_available_season_for_leagues('Fbref','Copa America')

{'id': 685, 'slug': 'Copa-America', 'season': {'2019', '2021', '2024'}}

In [29]:
fbref = ls.Fbref()
fbref.get_player_season_stats('stats','Copa America','2024')
#df_player = pd.DataFrame(datos_player)
#df_player.to_excel('player_euro_2024.xlsx')

Starting to scrape player data from Fbref...

KeyError: 'seasons'

In [39]:
fotmo.get_players_stats_season('Euros','2024',"rating")

Possible values for stat parameter: ['goals', 'goal_assist', '_goals_and_goal_assist', 'rating', 'goals_per_90', 'expected_goals', 'expected_goals_per_90', 'expected_goalsontarget', 'ontarget_scoring_att', 'total_scoring_att', 'accurate_pass', 'big_chance_created', 'total_att_assist', 'accurate_long_balls', 'expected_assists', 'expected_assists_per_90', '_expected_goals_and_expected_assists_per_90', 'won_contest', 'big_chance_missed', 'penalty_won', 'won_tackle', 'interception', 'effective_clearance', 'outfielder_block', 'penalty_conceded', 'poss_won_att_3rd', 'clean_sheet', '_save_percentage', 'saves', '_goals_prevented', 'goals_conceded', 'fouls', 'yellow_card', 'red_card']

,id,teamId,name,substatValue,statValue,rank,type,name,value,format,fractions
0,605654,6720,Fabián Ruiz,"{'value': 2, 'format': 'number', 'fractions': 0}","{'name': 'rating', 'value': 8.04, 'format': 'f...",1,players,rating,8.04,fraction,2
1,614834,6720,Dani Olmo,"{'value': 3, 'format': 'number', 'fractions': 0}","{'name': 'rating', 'value': 7.92, 'format': 'f...",2,players,rating,7.92,fraction,2
2,95078,8570,Toni Kroos,"{'value': 1, 'format': 'number', 'fractions': 0}","{'name': 'rating', 'value': 7.86, 'format': 'f...",3,players,rating,7.86,fraction,2
3,460632,8570,Joshua Kimmich,"{'value': 0, 'format': 'number', 'fractions': 0}","{'name': 'rating', 'value': 7.82, 'format': 'f...",4,players,rating,7.82,fraction,2
4,1061249,8361,Vitinha,"{'value': 1, 'format': 'number', 'fractions': 0}","{'name': 'rating', 'value': 7.76, 'format': 'f...",5,players,rating,7.76,fraction,2
...,...,...,...,...,...,...,...,...,...,...,...
300,700070,8565,Martin Adam,"{'value': 0, 'format': 'number', 'fractions': 0}","{'name': 'rating', 'value': 6, 'format': 'frac...",301,players,rating,6.00,fraction,2
301,599353,8498,Che Adams,"{'value': 0, 'format': 'number', 'fractions': 0}","{'name': 'rating', 'value': 5.95, 'format': 'f...",302,players,rating,5.95,fraction,2
302,737857,8205,Dusan Vlahovic,"{'value': 0, 'format': 'number', 'fractions': 0}","{'name': 'rating', 'value': 5.86, 'format': 'f...",303,players,rating,5.86,fraction,2
303,1225995,8496,Robin Hranac,"{'value': 0, 'format': 'number', 'fractions': 0}","{'name': 'rating', 'value': 5.83, 'format': 'f...",304,players,rating,5.83,fraction,2
304,668422,8498,Anthony Ralston,"{'value': 0, 'format': 'number', 'fractions': 0}","{'name': 'rating', 'value': 5.79, 'format': 'f...",305,players,rating,5.79,fraction,2